DROP FUNCTION IF EXISTS CHECK_SERVICE;
DELIMITER $$
CREATE  FUNCTION CHECK_SERVICE() 
RETURNS VARCHAR(40)
BEGIN
IF EXISTS(SELECT ID FROM SESSION_SCHEDULE WHERE CURTIME() BETWEEN START_TIME AND END_TIME) THEN
RETURN 'SERVICE IS PROVIDED';
ELSE 
RETURN 'NO SERVICE';
END IF;
END$$

DELIMITER ;

