DROP FUNCTION IF EXISTS SERVICE;
DELIMITER $$

CREATE FUNCTION CHECK_SERVICE()
RETURNS VARCHAR(50)
BEGIN
IF (CURTIME() < (SELECT START_TIME FROM SESSION_SCHEDULE WHERE ID=1)) THEN
RETURN "NO SERVICE";
ELSEIF (CURTIME() BETWEEN (SELECT END_TIME FROM SESSION_SCHEDULE WHERE ID=1) AND (SELECT START_TIME FROM SESSION_SCHEDULE WHERE ID=2)) THEN
RETURN "NO SERVICE";
ELSEIF (CURTIME() BETWEEN (SELECT END_TIME FROM SESSION_SCHEDULE WHERE ID=2) AND (SELECT START_TIME FROM SESSION_SCHEDULE WHERE ID=3))  THEN 
RETURN "NO SERVICE";
ELSEIF (CURTIME() > (SELECT END_TIME FROM SESSION_SCHEDULE WHERE ID=3)) THEN
RETURN "NO SERVICE";
ELSEIF (CURTIME() > (SELECT END_TIME FROM SESSION_SCHEDULE WHERE ID=4)) THEN
RETURN "NO SERVICE";
ELSE
RETURN "SERVICE IS PROVIDED";
END IF;
END $$
DELIMITER ;