DROP FUNCTION IF EXISTS SEAT_VERIFICATION;
DELIMITER $$
CREATE  FUNCTION SEAT_VERIFICATION(SEATNO INT) RETURNS INT(11)
BEGIN
DECLARE FLAG INT;
DECLARE SEATAVAILABILITY VARCHAR(30);
DECLARE TOGGLE_SEATS BOOLEAN;
SELECT CHECK_SEAT INTO TOGGLE_SEATS FROM SEAT WHERE SEAT_NO=SEATNO; 
SELECT STATUS INTO SEATAVAILABILITY FROM SEAT WHERE SEAT_NO=SEATNO;
IF SEATAVAILABILITY='AVAILABLE' 
THEN
IF TOGGLE_SEATS=FALSE
THEN
UPDATE SEAT SET CHECK_SEAT=TRUE WHERE SEAT_NO=SEATNO;
SET FLAG=1;
END IF;
ELSE
SET FLAG=0;
END IF;
RETURN FLAG;
END $$

DELIMITER ;