
DROP VIEW IF EXISTS STOCK_DETAILS;

CREATE VIEW STOCK_DETAILS AS 
SELECT `MENU_ITEMS`.`FOOD_ITEMS`,`SESSION_SCHEDULE`.`FOOD_TYPE`,ITEM_QUANTITY.`QTY`,
IFNULL(ITEM_QUANTITY.`QTY`-SUM(`ORDER_RECORDS`.`QTY`),ITEM_QUANTITY.`QTY`)
AS 'REMAINING QUANTITY',ORDER_RECORDS.`ORDER_DATE` AS 'TIME_DATE'
FROM ITEM_QUANTITY 
JOIN MENU_ITEMS,ORDER_RECORDS,SESSION_SCHEDULE
WHERE `MENU_ITEMS`.`ID`=ITEM_QUANTITY.`MENU_TYPE`
AND `SESSION_SCHEDULE`.`ID`=ITEM_QUANTITY.`FOOD_TYPE` 
AND `ORDER_RECORDS`.`FOOD_ITEM`=`MENU_ITEMS`.`FOOD_ITEMS` 
AND ORDER_RECORDS.`STATUS`='ORDERED'
AND DATE (ORDER_RECORDS.`ORDER_DATE`)= CURRENT_DATE() 
GROUP BY `MENU_ITEMS`.`FOOD_ITEMS`
 
 
 
 
SELECT * FROM STOCK_DETAILS;